[run]
init_cmds = [
    ["glide", "install"],
    ["go", "build"],
    ["./go-contix"]
]                                   # Commands run in start
watch_all = true                    # Watch all sub-directories
watch_dirs = [
    "$WORKDIR/commands",
    "$WORKDIR/configs",
    "$WORKDIR/models",
    "$WORKDIR/proxy",
    "$WORKDIR/utils",
]                                   # Directories to watch
watch_exts = [".go"]                # Extensions to watch
ignore = [".git", "data"]           # Directories to exclude from watching
ignore_files = []                   # Regexps for ignoring specific notifies
build_delay = 1500                  # Minimal interval to Trigger build event
interrupt_timout = 15               # Time to wait until force kill
graceful_kill = false               # Wait for exit and before directly kill
cmds = [
    ["go", "build"],
    ["./go-contix"]
]                                   # Commands to run
