usage:
	@echo "Commands     : Description"
	@echo "------------ : -----------"
	@echo "make install : Install the packages"
	@echo "make watch   : Watch the file changes and rebuild and reload them"

install:
	@npm install

watch:
	@npm run dev
